-- MySQL Script generated by MySQL Workbench
-- Sat Dec 28 21:36:53 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_tarefas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_tarefas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_tarefas` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `db_tarefas` ;

-- -----------------------------------------------------
-- Table `db_tarefas`.`tb_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_tarefas`.`tb_usuarios` (
  `usuario_id` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario_senha` VARCHAR(12) NOT NULL,
  `usuario_nome` VARCHAR(45) NOT NULL,
  `usuario_email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usuario_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `db_tarefas`.`tb_tarefas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_tarefas`.`tb_tarefas` (
  `tarefas_id` INT(11) NOT NULL AUTO_INCREMENT,
  `tarefas_titulo` VARCHAR(45) NOT NULL,
  `tarefas_finalizada` BIT(1) NOT NULL,
  `tb_usuarios_usuario_id` INT(11) NOT NULL,
  PRIMARY KEY (`tarefas_id`, `tb_usuarios_usuario_id`),
  INDEX `fk_tb_tarefas_tb_usuarios_idx` (`tb_usuarios_usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_tarefas_tb_usuarios`
    FOREIGN KEY (`tb_usuarios_usuario_id`)
    REFERENCES `db_tarefas`.`tb_usuarios` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

USE `db_tarefas` ;

-- -----------------------------------------------------
-- procedure db_tarefas
-- -----------------------------------------------------

DELIMITER $$
USE `db_tarefas`$$
CREATE DEFINER=`db_tarefas`@`localhost` PROCEDURE `db_tarefas`()
BEGIN

END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
